version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    - image: circleci/mysql:5.7.21
      environment:
        MYSQL_USER: root

    working_directory: /go/src/github.com/lab259/http-mysql-service
    steps:
      - checkout

      - run: sudo apt install mysql-client libssl-dev

      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://localhost:3306 -timeout 10s

      - run: go get -u github.com/onsi/ginkgo/ginkgo
      - run: make deps-ci
      - run: make test
      - run: make coverage-ci
      - run: bash <(curl -s https://codecov.io/bash)
